<br /><br />
<div id="view-content">
	<p>View script for controller <b>Friendship</b> and script/action name <b>delete</b></p>
</div>

<?php
// the variable/array 'friendship' and 'form' is generated and set in the
// controller 'friendship' and action 'delete'
//
// all functions to the model friendship like 'getId()' and 'getFirstname() are
// functions of the model 'friendship' in the file 'models\friendship.php
?>

<?php $friendship = $this->friendship; ?>

<div class="page-header">
	<a class="pull-right" href="<?php echo $this->url(array('controller' => 'friendship', 'action' => 'view', 'id' => $friendship->getId())); ?>"><button type="button" class="btn btn-default">Abbrechen</button></a>
	<h3>Benutzer löschen</h3>
</div>

<div class="alert alert-danger alert-dismissible fade in" role=alert>
	<!--<button type=button class=close data-dismiss=alert aria-label=Close><span aria-hidden=true>&times;</span></button>-->
	<h4><?php echo $friendship->getPerson1() . ' ' . $friendship->getPrson2(); ?></h4>
	<p>Change this and that and try again. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum.</p>
	<p></p>
	<a class="pull-right" href="<?php echo $this->url(array('controller' => 'friendship', 'action' => 'view', 'id' => $friendship->getId())); ?>"><button type="button" class="btn btn-default">Abbrechen</button></a>
	<?php echo $this->form; ?>
</div>
