<div id="view-content">
	<p>View script for controller <b>Friendship</b> and script/action name <b>view</b></p>
</div>

<?php
// the variable/array 'user' is generated and set in the
// controller 'user' and action 'view'
//
// all functions to the model user like 'getId()' and 'getFirstname() are
// functions of the model 'user' in the file 'models\user.php
?>

<?php $friendship = $this->friendship; ?>

<div class="page-header">
	<a class="pull-right" href="<?php echo $this->url(array('controller' => 'friendship', 'action' => 'update', 'id' => $friendship->getId())); ?>"><button type="button" class="btn btn-default">Bearbeiten</button></a>
	<a class="pull-right" href="<?php echo $this->url(array('controller' => 'friendship', 'action' => 'delete', 'id' => $friendship->getId())); ?>"><button type="button" class="btn btn-default">Löschen</button></a>
	<h3>Benutzer</h3>
</div>
<div class="jumbotron">
	<div class="media">
	  <div class="media-left">
		  <img alt="Generic placeholder image" class="media-object" data-src="holder.js/400x300?bg=2a2025">
	  </div>
	  <div class="media-body">
		<h1><?php echo $friendship->getFirstname() . ' ' . $friendship->getLastname(); ?></h1>
		<h2>Freundschafts ID #<?php echo $friendship->getId(); ?></h2>
		<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
		<p><a href="mailto:<?php echo $friendship->getEmail(); ?>"><?php echo $friendship->getEmail(); ?></a></p>
	  </div>
	</div>
</div>
